name: example
description: A project used to demo the Circular Reveal Animation
version: 1.0.0+1

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  circular_reveal_animation:
    path: ../
  url_launcher: ^6.0.0-nullsafety.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/